# Generated by Django 4.2.1 on 2023-05-24 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_for_hk',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
