# Generated by Django 4.2.1 on 2023-06-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_version_previous_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='previous_version',
        ),
    ]
