# Generated by Django 4.2.1 on 2023-06-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_product_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_cancel_product_publication', 'Can cancel product publication'), ('can_change_product_description', 'Can change product description'), ('can_change_product_category', 'Can change product category')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
