# Generated by Django 4.2.1 on 2023-06-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_product_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('create_product', 'Can Create Product'), ('update_product', 'Can update product')), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
